<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

# Exercise 1 (Total recall)

| Term       | Brief description |
|------------|-------------------|
| Subsetting | Select a sub-group.                  |
| Indexing   | Selecting elements.                  |
| Slicing    | Splitting up a list _(selecting a range of elements)_.                  |
| Masking    | Subsetting based on True/False condition.                  |

# Exercise 2 (Show me the ‘odd’ letters) 

In [38]:
#EXPERIMENT
print(np_array_2d[:3,1]) # '0' returns keys, '1' returns values

['A' 'C' 'B']


In [37]:
import numpy as np

np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

numbers = np_array_2d[:,0] #select only numbers
numbers = numbers.astype(int) #convert to int
odd = numbers%2 #even numbers will have no remainder
odd = odd != 0 #'odd' is now an array of TRUE for odd, FALSE for even

print(np_array_2d[odd,1]) #printing the mask, only values.

['A' 'C' 'E' 'G' 'I']


# Exercise 3

In [27]:
import numpy as np

funny_list = [[66, 50, 57, -1, -1],
 [92, -1, 88, -1, -1],
 [75, -1, -1, 76, -1],
 [-1, 51, 87, -1, -1],
 [71, -1, 67, -1, 69]]

funny_array = np.array(funny_list)

big_number = funny_array < 50 #mask

# big_number = big_number - (big_number + 1) #This manages to change everything into -1

#if big_number.any() == True:
#    big_number = -1 #This didn't really work :(

print(big_number) #just checking

funny_array[big_number] = -1

print(funny_array)

[[False False False  True  True]
 [False  True False  True  True]
 [False  True  True False  True]
 [ True False False  True  True]
 [False  True False  True False]]
[[66 50 57 -1 -1]
 [92 -1 88 -1 -1]
 [75 -1 -1 76 -1]
 [-1 51 87 -1 -1]
 [71 -1 67 -1 69]]


In [29]:
small_number = funny_array > 50
funny_array[small_number] = 1
print(funny_array)

[[ 1 50  1 -1 -1]
 [ 1 -1  1 -1 -1]
 [ 1 -1 -1  1 -1]
 [-1  1  1 -1 -1]
 [ 1 -1  1 -1  1]]


In [1]:
exactly_50 = funny_array == 50 #making a mask 
funny_array[exactly_50] = 0 #subset, then, change value to 0
print(funny_array)

NameError: name 'funny_array' is not defined