<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

# What to expect in this chapter

# 1 Lists, Arrays & Dictionaries

In [10]:
'list'=[1,2,3,4,5] #DO NOT use "list" as a variable, it is python keyword. Function will be overidded. 

SyntaxError: cannot assign to literal here. Maybe you meant '==' instead of '='? (3026366143.py, line 1)

In [12]:
#example
print=2
print ('hahaha')

TypeError: 'int' object is not callable

In [15]:
import numpy as np

In [22]:
py_list=[1,2,3,4,5] #for growing numbers, adding to list. Convert to numpy_array before calculations.

In [18]:
py_list

[1, 2, 3, 4, 5]

In [19]:
np_array=np.array([1,2,3,4,5]) #for math and science calculations

In [21]:
np_array

array([1, 2, 3, 4, 5])

In [23]:
np_array=np.array(py_list)

## 1.1 Let’s compare

## 1.2 Accessing data from a list (or array)

## 1.3 Accessing data from a dictionary

## 1.4 Higher dimensional lists

# 2 Lists vs. Arrays

In [27]:
#list works as a whole
#arrays works with individual elements within

py_list +1

TypeError: can only concatenate list (not "int") to list

In [35]:
np_array +1 #add 1 to each element

array([2, 3, 4, 5, 6])

In [36]:
py_list +[1] #add [1] to the list

[1, 2, 3, 4, 5, 1]

In [37]:
py_list*2 #make the list twice

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [39]:
np_array*2 #multiply each element by 2

array([ 2,  4,  6,  8, 10])

In [40]:
len(py_list) #length of list

5

In [46]:
len(np_array) 

5

In [47]:
np_array.size #size of array aka length

5

In [45]:
np_array.shape

(5,)

In [48]:
#asking question
'a' in ['a','b','c']

True

In [54]:
my_rand_numbers=np.random.randint(0,100,10)
my_rand_numbers

array([39,  6, 97, 58, 27, 35, 89,  6,  7, 68], dtype=int32)

In [55]:
my_rand_numbers<50

array([ True,  True, False, False,  True,  True, False,  True,  True,
       False])

In [56]:
mask=my_rand_numbers<50
my_rand_numbers[mask]

array([39,  6, 27, 35,  6,  7], dtype=int32)

In [60]:
mask=(my_rand_numbers<50)&(my_rand_numbers%2==0)
my_rand_numbers[mask]

array([6, 6], dtype=int32)

In [63]:
my_rand_numbers[-1] 
#[] after an array is subsetting an array.
#start counting from 0
#negative numbers to count from the back without needing the know the size of the array

np.int32(68)

In [67]:
py_2d_list=[[1,2,3],[4,5,6],[7,8,9]] #list in a list
py_2d_list[0]

[1, 2, 3]

In [70]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)      # Reusing the Python list 
                                        # to create a NEW
                                        # NumPy array

In [72]:
py_list_2d

[[1, 'A'],
 [2, 'B'],
 [3, 'C'],
 [4, 'D'],
 [5, 'E'],
 [6, 'F'],
 [7, 'G'],
 [8, 'H'],
 [9, 'I'],
 [10, 'J']]

In [74]:
np_array_2d #everything converted to str

array([['1', 'A'],
       ['2', 'B'],
       ['3', 'C'],
       ['4', 'D'],
       ['5', 'E'],
       ['6', 'F'],
       ['7', 'G'],
       ['8', 'H'],
       ['9', 'I'],
       ['10', 'J']], dtype='<U21')

- numpy arrays do not tolerate different types (optimised for array operations, different types will slow it down, converts lists all into the same type)
- lists allows different types eg. str, int, etc.

In [77]:
py_list_2d[0][1] #indexing

'A'

In [76]:
np_array_2d[0,1]

np.str_('A')

In [89]:
#Python Lists

py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

#Numpy Arrays

np_super_names = np.array(["Black Widow", "Iron Man", "Doctor Strange"])
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])

#Dictionary

superhero_info = {
    "Natasha Romanoff": ["Black Widow","Blue Mouse","Pink Tiger"],
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange"
}
#storing data with KEY and VALUE, access data
#dictionary can contain lists, arrays, dictionaries
#case-sensitive

In [81]:
superhero_info['Tony Stark']

'Iron Man'

In [88]:
superhero_info['Natasha Romanoff'][1] #indexing a list within a dictionary

'Blue Mouse'

In [87]:
#PySuperNames

In [91]:
py_list=["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"]
np_array=np.array(py_list)

# Pick one
x = py_list  # OR
x = np_array

In [102]:
py_list[3:6] #SLICING = subset a range, returns positions 3,4,5 ONLY

['d4', 'e5', 'f6']

In [93]:
py_list[3:]

['d4', 'e5', 'f6', 'g7', 'h8', 'i9', 'j10']

In [95]:
py_list[:-2]

['a1', 'b2', 'c3', 'd4', 'e5', 'f6', 'g7', 'h8']

In [100]:
py_list[-1::-1] #REVERSE from end to start, going backwards

['j10', 'i9', 'h8', 'g7', 'f6', 'e5', 'd4', 'c3', 'b2', 'a1']

In [101]:
py_list[::2] #SKIPPING

['a1', 'c3', 'e5', 'g7', 'i9']

In [103]:
py_list=["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"]
np_array=np.array(py_list)

# Pick one
x = py_list  # OR
x = np_array

In [104]:
py_list_2d[1:4]

[[2, 'B'], [3, 'C'], [4, 'D']]

In [105]:
np_array_2d[:,0]

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'], dtype='<U21')

In [108]:
#convert to int to do math
np_array_2d[1:4,0].astype(int)*2

array([4, 6, 8])

In [109]:
#for lists
py_list_again=[1,2]+[8,9,0]+['A','B']

In [114]:
py_list_again #concatenate

[1, 2, 8, 9, 0, 'A', 'B']

In [113]:
#for arrays
np.array([1,2,3])+np.array([8,9,0]) #math: will calculate the value of the addition of each elements

array([ 9, 11,  3])

## 2.1 Size

## 2.2 Arrays are fussy about type

## 2.3 Adding a number

## 2.4 Adding another list

## 2.5 Multiplying by a Number

## 2.6 Squaring

## 2.7 Asking questions

## 2.8 Mathematics

## Footnotes

In [115]:
x=[1,2,3]

In [116]:
x[0]=1000

In [117]:
x

[1000, 2, 3]

In [121]:
y=(1,2,3) #TUPLES have list attributes but cannot be changed eg. for experiment constants.

In [120]:
y[0]=1000

TypeError: 'tuple' object does not support item assignment

In [2]:
x=[1, 2, 3]
y=x           # DON'T do this!
z=x           # DON'T do this!
print(f'Before: {x=},{y=},{z=}')
x[0]=1000
print(f'After: {x=},{y=},{z=}')

Before: x=[1, 2, 3],y=[1, 2, 3],z=[1, 2, 3]
After: x=[1000, 2, 3],y=[1000, 2, 3],z=[1000, 2, 3]
